name: dunfell

on:
  workflow_dispatch:

jobs:
  runqemu:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: recursive
      - name: build Docker
        run: ./build-docker.sh
      - name: build Yocto
        run: ./server-run-docker.sh ./build.sh
      - name: runqemu swift hello world
        run: ./server-run-docker.sh ./execute.exp

