name: CI

on:
  workflow_dispatch:

jobs:
  runqemu:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false
      - name: build Docker
      - run: ./build-docker.sh 

